### PR TITLE
Fix licence and update JGRAPHT to 0.9.2

### PR DESCRIPTION
**Pull request by ebocher**

### CODE REVIEW

**Comment by ebocher** [comment]
It seems that Jgrapht 1.0 compiles at least with the JAVA 8

**Comment by ebocher** [comment]
What about H2gis ?

**Comment by ebocher** [comment]
Ready to merge

**Comment by nicolas-f** [comment]
Will have to release this to maven central before updating dependency in h2gis

**Comment by ebocher** [comment]
Yes a stable release

**Pull request merged**
